name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: "1.21"
          check-latest: true
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@0adbc47a5910e47adb692df88187ec8c73c76778 # v3.7.1
        with:
          version: v1.60.3
